---
name: Renovate
on:
  schedule:
    - cron: '42 * * * *'
  pull_request:
    branches:
      - master

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - name: Enable dry-run
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      # https://github.com/renovatebot
      - uses: renovatebot/github-action@95cbcd7e8b9d0d69e15ba26208631839ce7eee48 # v36.0.2
        with:
          # https://docs.renovatebot.com/self-hosted-configuration
          configurationFile: default.json
          # FIXME: switch to ephemeral token
          token: ${{ secrets.FLOWZONE_TOKEN }}
        env:
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
          RENOVATE_HOST_RULES: |
            [
              {
                "hostType": "docker",
                "username": "${{ secrets.DOCKERHUB_USER }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              },
              {
                "hostType": "docker",
                "matchHost": "ghcr.io",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]
