---
name: Renovate
on:
  schedule:
    - cron: '42 * * * *'
  pull_request:
    branches:
      - master

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Enable dry-run
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      # https://github.com/renovatebot
      - uses: renovatebot/github-action@ddc7c2d18a8be56d49db4bf068f2a9e4323d723a # v34.130.0
        with:
          # https://docs.renovatebot.com/configuration-options
          configurationFile: .github/renovate.json
          token: ${{ secrets.FLOWZONE_TOKEN }}
        env:
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
          RENOVATE_HOST_RULES: '[{"hostType":"docker","username":"${{ env.DOCKERHUB_USER }}","password":"${{ secrets.DOCKERHUB_TOKEN }}"}]'
