---
name: Renovate
on:
  schedule:
    - cron: '42 * * * *'
  pull_request:
    branches:
      - master

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Enable dry-run
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'

      # https://github.com/renovatebot
      - uses: renovatebot/github-action@5e8129624e65d182d7dc0fa673708ff4badab949 # v34.159.1
        with:
          # https://docs.renovatebot.com/self-hosted-configuration
          configurationFile: default.json
          # FIXME: switch to ephemeral token
          token: ${{ secrets.FLOWZONE_TOKEN }}
        env:
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
          RENOVATE_HOST_RULES: |
            [
              {
                "hostType": "docker",
                "username": "${{ secrets.DOCKERHUB_USER }}",
                "password": "${{ secrets.DOCKERHUB_TOKEN }}"
              },
              {
                "hostType": "docker",
                "matchHost": "ghcr.io",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]
